title: GitHub Practice Lab
author: mchave01
email: mchave01@g.uafs.edu
description: > # this means to ignore newlines until "baseurl:"
Practice for github pages by mchave01. 

# social links
#twitter_username: your-twitter-handle
github_username:  mchave01

show_excerpts: true # set to false to remove excerpts on the homepage

# theme for this page
theme: minima
